# Site settings
title: This is the blog of Ayo Kolapo
email: helloayokolapo@gmail.com
description: > # This is the blog of Ayo Kolapo
baseurl: "" # the subpath of your site, e.g. /blog
url: "ayokolapo.com" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', 'https://www.linkedin.com/in/ayokolapo', 'fa-user']
single_footer: '<p> Ayo Kolapo &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Ayo Kolapo 2016', '/about']


# Build settings
markdown: kramdown
